### ISSUE TITLE
Hadoop-BAM mvn test

### ISSUE THREAD

**Issue by linhbngo** [HadoopGenomics/Hadoop-BAM#117]
When I run the "mvn test" command, I receive the following errors:

Tests in error:
  TestBAMOutputFormat.testBAMOutput:152->doMapReduce:258 » FileAlreadyExists Out...
  TestBAMOutputFormat.testBAMRoundTrip:217->doMapReduce:258 » FileAlreadyExists ...
  TestBAMOutputFormat.testBAMWithSplittingBai:185 » FileSystem /home/lngo/git/Ha...
  TestSAMInputFormat.testMapReduceJob:89 » FileAlreadyExists Output directory fi...
  TestVCFRoundTrip.testRoundTripWithMerge:197->doMapReduce:249 » FileAlreadyExists
  TestVCFRoundTrip.testRoundTripWithMerge:197->doMapReduce:249 » FileAlreadyExists
  TestVCFRoundTrip.testRoundTripWithMerge:197->doMapReduce:249 » FileAlreadyExists
  TestVCFRoundTrip.testRoundTripWithMerge:197->doMapReduce:249 » FileAlreadyExists
  TestVCFRoundTrip.testRoundTripWithMerge:197->doMapReduce:249 » FileAlreadyExists
  TestVCFRoundTrip.testRoundTripWithMerge:197->doMapReduce:249 » FileAlreadyExists
  TestVCFRoundTrip.testRoundTripWithMerge:197->doMapReduce:249 » FileAlreadyExists
  TestVCFRoundTrip.testRoundTripWithMerge:197->doMapReduce:249 » FileAlreadyExists
  TestVCFRoundTrip.testRoundTrip:144->doMapReduce:249 » FileAlreadyExists Output...
  TestVCFRoundTrip.testRoundTrip:144->doMapReduce:249 » FileAlreadyExists Output...
  TestVCFRoundTrip.testRoundTrip:144->doMapReduce:249 » FileAlreadyExists Output...
  TestVCFRoundTrip.testRoundTrip:144->doMapReduce:249 » FileAlreadyExists Output...
  TestVCFRoundTrip.testRoundTrip:144->doMapReduce:249 » FileAlreadyExists Output...
  TestVCFRoundTrip.testRoundTrip:144->doMapReduce:249 » FileAlreadyExists Output...
  TestVCFRoundTrip.testRoundTrip:144->doMapReduce:249 » FileAlreadyExists Output...

Tests run: 175, Failures: 0, Errors: 19, Skipped: 0

I wonder this is an issue with multiple test cases receive the same input/output directory and need to have these output directories reset to comply with HDFS' requirement to have MR output directory to not exist yet.

**Comment by rofithah** [comment]
Hi, i do the same test.. at first I run the mvn test, it doesnt work. then.. I tried using maven 3.5.0 and run it again.. and it successful. I hope this can help you.. i install maven 3.5.0 inside /etc/opt.. then export path of maven. 

After that, inside Hadoop-BAM i run the test like this:

 /etc/opt/apache-maven-3.5.0/bin/mvn test 

Results :
Tests run: 178, Failures: 0, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:07 min
[INFO] Finished at: 2017-09-20T14:41:49+07:00
[INFO] Final Memory: 21M/260M
[INFO] ------------------------------------------------------------------------

**Comment by tomwhite** [comment]
This should now be fixed by #162
