### ISSUE TITLE
NIOFileUtil.deleteRecursive delete if exists

### ISSUE THREAD

**Issue by david-wb** [HadoopGenomics/Hadoop-BAM#131]
Hi, 

I am using an Amazon S3 NIO library and seeing a small issue in the `NIOFileUtil.deleteRecursive` function. S3 has no concept of directories, so once all of the files have been deleted, the parent folder not longer exists. This causes the final `postVisitDirectory()` method to throw a `NoSuchFile` exception. Would it be reasonable to change `deleteRecursive()` to use `Files.deleteIfExists()` inside `postVisitDirectory()` like so? 

```
  static void deleteRecursive(Path directory) throws IOException {
    Files.walkFileTree(directory, new SimpleFileVisitor<Path>() {
      @Override
      public FileVisitResult visitFile(Path file, BasicFileAttributes attrs) throws IOException {
        Files.delete(file);
        return FileVisitResult.CONTINUE;
      }
      @Override
      public FileVisitResult postVisitDirectory(Path dir, IOException exc) throws IOException {
        Files.deleteIfExists(dir);
        return FileVisitResult.CONTINUE;
      }
    });
  }
```

Thanks,
David

**Comment by tomwhite** [comment]
This seems very reasonable. I've created a fix in #163.
