### ISSUE TITLE
Enable VCF output format to write GVCF

### ISSUE THREAD

**Issue by tomwhite** [HadoopGenomics/Hadoop-BAM#134]

**Comment by fnothaft** [comment]
@tomwhite OOC, what is the limitation here? We've been using Hadoop-BAM to write out gVCFs from ADAM for a while.

**Comment by tomwhite** [comment]
@fnothaft oh interesting. In my experiments I found I had to make it possible for VariantContextWriter to be set by subclasses of VCFRecordWriter. I may be looking at it the wrong way though.

**Comment by fnothaft** [comment]
Hmmm, yeah, we haven't seen any such issues from ADAM. Is the GATK emitting a special subclass of VariantContext for gVCF records?

**Comment by tomwhite** [comment]
Yes, that's it. The relevant changes are https://github.com/HadoopGenomics/Hadoop-BAM/pull/137 and https://github.com/broadinstitute/gatk/commit/042d756e168903daeb1eb3a8c0a976694d443a9a. GATK uses a special VariantContextWriter for gVCF files, and these changes make it possible to use it.

I had a quick look at ADAM but couldn't see where the gVCF writing code is. Any pointers you have would be appreciated.

**Comment by fnothaft** [comment]
Hi @tomwhite! Apologies for the slow reply. We don't have a special writer for gVCF because the expectation is that if you want gVCF bands, you'll band the genotype qualities in your `org.bdgenomics.formats.avro.Genotype`s before converting to `VariantContext`s and saving as gVCF.

**Comment by tomwhite** [comment]
Fixed in #137 (and used in https://github.com/broadinstitute/gatk/pull/3450)
