### ISSUE TITLE
Reformat source code for consistent use of whitespace

### ISSUE THREAD

**Issue by heuermh** [HadoopGenomics/Hadoop-BAM#147]
At a minimum we'd have to agree on:

Use tab characters or spaces  (spaces)
Tab/indent size  (2 or 4)
Space before parens  (1)
Space around operators  (1)
Space before left brace  (1)
Space before keywords  (1)
Space in ternary operator  (1)
Space after comma in type arguments  (1)
Space after comma  (1)
Space after type cast  (1)
Else on new line  (Yes)
Right margin  (120 columns)

My preferences in parens.  I'd suggest doing this with a source code formatter all in one commit after the next release.

**Comment by fnothaft** [comment]
+1 on all except for right margin where my pref is 80.

**Comment by heuermh** [comment]
Closing as WontFix
