### ISSUE TITLE
problem with running the sort command

### ISSUE THREAD

**Issue by gchen98** [HadoopGenomics/Hadoop-BAM#15]
I have two questions. First, an easier one I think:

For some reason when using the hadoop-bam.jar that doesn't include dependencies, I get a class not found "sort" when running the command as shown in the documentation.  However, if I run 

hadoop jar Hadoop-BAM-master/target/hadoop-bam-7.0.1-SNAPSHOT.jar org.seqdoop.hadoop_bam.cli.Frontend -libjars /home/garychen1/hadoop/htsjdk-1.128.jar,/home/garychen1/hadoop/commons-jexl-2.1.1.jar sort -v --format=BAM workdir bamfiles/CG-0013A.1q31.bam

the MapReduce appears to begin correctly.

Alternatively I can run

hadoop jar Hadoop-BAM-master/target/hadoop-bam-7.0.1-SNAPSHOT-jar-with-dependencies.jar -libjars /home/garychen1/hadoop/htsjdk-1.128.jar,/home/garychen1/hadoop/commons-jexl-2.1.1.jar sort -v --format=BAM workdir bamfiles/CG-0013A.1q31.bam

and this also starts the MapReduce job.

My second question is as follows:

WIth either command above I start the map jobs, but part way through the reduce jobs. I get an error message:

[garychen1@biocluster hadoop]$ hadoop jar Hadoop-BAM-master/target/hadoop-bam-7.0.1-SNAPSHOT.jar org.seqdoop.hadoop_bam.cli.Frontend -libjars /home/garychen1/hadoop/htsjdk-1.128.jar,/home/garychen1/hadoop/commons-jexl-2.1.1.jar sort -v --format=BAM workdir bamfiles/CG-0013A.1q31.bam
15/02/13 07:11:33 INFO Configuration.deprecation: mapred.reduce.tasks is deprecated. Instead, use mapreduce.job.reduces
sort :: Sampling...
15/02/13 07:11:33 INFO input.FileInputFormat: Total input paths to process : 1
15/02/13 07:11:42 INFO partition.InputSampler: Using 10000 samples
15/02/13 07:11:42 INFO zlib.ZlibFactory: Successfully loaded & initialized native-zlib library
15/02/13 07:11:42 INFO compress.CodecPool: Got brand-new compressor [.deflate]
sort :: Sampling complete in 9.491 s.
15/02/13 07:11:43 INFO client.RMProxy: Connecting to ResourceManager at biocluster.med.usc.edu/68.181.163.131:8032
15/02/13 07:11:43 INFO input.FileInputFormat: Total input paths to process : 1
15/02/13 07:11:43 INFO mapreduce.JobSubmitter: number of splits:3
15/02/13 07:11:43 INFO mapreduce.JobSubmitter: Submitting tokens for job: job_1423785861813_0007
15/02/13 07:11:43 INFO impl.YarnClientImpl: Submitted application application_1423785861813_0007
15/02/13 07:11:44 INFO mapreduce.Job: The url to track the job: http://biocluster.med.usc.edu:8088/proxy/application_1423785861813_0007/
sort :: Waiting for job completion...
15/02/13 07:11:44 INFO mapreduce.Job: Running job: job_1423785861813_0007
15/02/13 07:11:49 INFO mapreduce.Job: Job job_1423785861813_0007 running in uber mode : false
15/02/13 07:11:49 INFO mapreduce.Job:  map 0% reduce 0%
15/02/13 07:11:59 INFO mapreduce.Job:  map 46% reduce 0%
15/02/13 07:12:02 INFO mapreduce.Job:  map 67% reduce 0%
15/02/13 07:12:05 INFO mapreduce.Job:  map 78% reduce 0%
15/02/13 07:12:08 INFO mapreduce.Job:  map 89% reduce 0%
15/02/13 07:12:11 INFO mapreduce.Job:  map 100% reduce 0%
15/02/13 07:12:15 INFO mapreduce.Job:  map 100% reduce 22%
15/02/13 07:12:15 INFO mapreduce.Job: Task Id : attempt_1423785861813_0007_r_000000_0, Status : FAILED
Error: Found interface org.apache.hadoop.mapreduce.TaskAttemptContext, but class was expected
15/02/13 07:12:16 INFO mapreduce.Job:  map 100% reduce 0%
15/02/13 07:12:27 INFO mapreduce.Job:  map 100% reduce 11%
15/02/13 07:12:36 INFO mapreduce.Job:  map 100% reduce 22%
15/02/13 07:12:38 INFO mapreduce.Job: Task Id : attempt_1423785861813_0007_r_000000_1, Status : FAILED
Error: Found interface org.apache.hadoop.mapreduce.TaskAttemptContext, but class was expected
15/02/13 07:12:39 INFO mapreduce.Job:  map 100% reduce 0%
15/02/13 07:12:50 INFO mapreduce.Job:  map 100% reduce 22%
15/02/13 07:13:02 INFO mapreduce.Job: Task Id : attempt_1423785861813_0007_r_000000_2, Status : FAILED
Error: Found interface org.apache.hadoop.mapreduce.TaskAttemptContext, but class was expected
15/02/13 07:13:03 INFO mapreduce.Job:  map 100% reduce 0%
15/02/13 07:13:13 INFO mapreduce.Job:  map 100% reduce 100%
15/02/13 07:13:14 INFO mapreduce.Job: Job job_1423785861813_0007 failed with state FAILED due to: Task failed task_1423785861813_0007_r_000000
Job failed as tasks failed. failedMaps:0 failedReduces:1

15/02/13 07:13:14 INFO mapreduce.Job: Counters: 37
	File System Counters
		FILE: Number of bytes read=1072859902
		FILE: Number of bytes written=2146049435
		FILE: Number of read operations=0
		FILE: Number of large read operations=0
		FILE: Number of write operations=0
		HDFS: Number of bytes read=331721757
		HDFS: Number of bytes written=0
		HDFS: Number of read operations=15
		HDFS: Number of large read operations=0
		HDFS: Number of write operations=0
	Job Counters 
		Failed reduce tasks=4
		Launched map tasks=3
		Launched reduce tasks=4
		Data-local map tasks=3
		Total time spent by all maps in occupied slots (ms)=53765
		Total time spent by all reduces in occupied slots (ms)=59825
		Total time spent by all map tasks (ms)=53765
		Total time spent by all reduce tasks (ms)=59825
		Total vcore-seconds taken by all map tasks=53765
		Total vcore-seconds taken by all reduce tasks=59825
		Total megabyte-seconds taken by all map tasks=55055360
		Total megabyte-seconds taken by all reduce tasks=61260800
	Map-Reduce Framework
		Map input records=6056948
		Map output records=6056948
		Map output bytes=1054688968
		Map output materialized bytes=1072859830
		Input split bytes=399
		Combine input records=0
		Spilled Records=12113896
		Failed Shuffles=0
		Merged Map outputs=0
		GC time elapsed (ms)=465
		CPU time spent (ms)=58340
		Physical memory (bytes) snapshot=794177536
		Virtual memory (bytes) snapshot=2741903360
		Total committed heap usage (bytes)=565968896
	File Input Format Counters 
		Bytes Read=0
sort :: Job failed.
[garychen1@biocluster hadoop]

I dug in the logs
and I got 8 container_* directories under the userlogs/application_* directory. In the last 4 container_* directories, I found a stack trace with the following:

2015-02-13 07:12:14,868 FATAL [main] org.apache.hadoop.mapred.YarnChild: Error r
unning child : java.lang.IncompatibleClassChangeError: Found interface org.apach
e.hadoop.mapreduce.TaskAttemptContext, but class was expected
        at org.seqdoop.hadoop_bam.cli.Utils.getMergeableWorkFile(Utils.java:180)
        at org.seqdoop.hadoop_bam.cli.CLIMergingAnySAMOutputFormat.getDefaultWorkFile(CLIMergingAnySAMOutputFormat.java:69)
        at org.seqdoop.hadoop_bam.cli.CLIMergingAnySAMOutputFormat.getRecordWriter(CLIMergingAnySAMOutputFormat.java:62)
        at org.apache.hadoop.mapred.ReduceTask$NewTrackingRecordWriter.<init>(ReduceTask.java:540)
        at org.apache.hadoop.mapred.ReduceTask.runNewReducer(ReduceTask.java:614)
        at org.apache.hadoop.mapred.ReduceTask.run(ReduceTask.java:389)
        at org.apache.hadoop.mapred.YarnChild$2.run(YarnChild.java:163)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:415)
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1628)
        at org.apache.hadoop.mapred.YarnChild.main(YarnChild.java:158)

Do you have any insights into this? I build hadoop from source as well as all the other dependencies of hadoop-bam.

I am running Hadoop version 2.6.0:

[garychen1@biocluster ~]$ hadoop version
Hadoop 2.6.0
Subversion Unknown -r Unknown
Compiled by garychen1 on 2015-02-12T23:40Z
Compiled with protoc 2.5.0
From source with checksum 18e43357c8f927c0695f1e9522859d6a
This command was run using /home/garychen1/hadoop/hadoop-2.6.0-src/hadoop-dist/target/hadoop-2.6.0/share/hadoop/common/hadoop-common-2.6.0.jar
[garychen1@biocluster ~]$ 

Thanks! Let me know if you need further information.

Gary

**Comment by gchen98** [comment]
I was able to resolve the 2nd problem.  I guess it turns out in the pom.xml of the Hadoop BAM distribution, I just needed to update the hadoop version number to the correct value, and rebuild the problem.  However, if you have any ideas regarding my first question that would be great.

**Comment by AndreSchumacher** [comment]
Hi @gchen98 sorry for the late reply. After you changed the <tt>pom.xml</tt>, did you try re-running it using the <tt>*-jar-with-dependencies.jar</tt>?

**Comment by gchen98** [comment]
Yeah, everything is OK now. Thanks.
