### ISSUE TITLE
BAMReordReader: CIGAR M operator maps off end of reference

### ISSUE THREAD

**Issue by seppinho** [HadoopGenomics/Hadoop-BAM#174]
Hi all,
does HadoopBAM has a flag to set ValidationStringency to LENIENT? Problem occurs for mitochondrial (circular) reads with primary and secondary alignment.
thx

**Comment by cmnbroad** [comment]
Yes, though it looks like its not documented in the README. You should be able to set the "hadoopbam.samheaderreader.validation-stringency" to LENIENT.

**Comment by seppinho** [comment]
@cmnbroad awesome! works.
conf.set("hadoopbam.samheaderreader.validation-stringency", "LENIENT");
