### ISSUE TITLE
Update to new HTSJDK API

### ISSUE THREAD

**Issue by AndreSchumacher** [HadoopGenomics/Hadoop-BAM#18]
There are plenty of deprecation warning when building that we should take care of.

**Comment by tomwhite** [comment]
We updated to htsjdk 1.140 in https://github.com/HadoopGenomics/Hadoop-BAM/pull/28, so this can be closed.

**Comment by AndreSchumacher** [comment]
I'm still seeing warnings regarding htsjdk.samtools.SAMFileReader and parts of the HTSJDK VCF API we use being deprecated. They are easier to spot if one adds deprecation warnings to the compile plugin. I'll break those out into several issues and then close this one here.

**Comment by tomwhite** [comment]
Ah yes, I see them now. There are over 50 warnings to fix, so best to break out.

**Comment by tomwhite** [comment]
I've opened https://github.com/HadoopGenomics/Hadoop-BAM/pull/38 to fix the htsjdk deprecations. There are still Hadoop API deprecations, but they can be addressed separately since they weren't caused by updating the htsjdk library.
