### ISSUE TITLE
SeekableStreams in BAMInputFormat.java aren't closed

### ISSUE THREAD

**Issue by akmorrow13** [HadoopGenomics/Hadoop-BAM#187]
In addProbabilisticSplits, a SeekableStream is opened and closed. However, in addBAISplits, three SeekableStreams are opened:
https://github.com/HadoopGenomics/Hadoop-BAM/blob/master/src/main/java/org/seqdoop/hadoop_bam/BAMInputFormat.java#L335 and

https://github.com/HadoopGenomics/Hadoop-BAM/blob/master/src/main/java/org/seqdoop/hadoop_bam/BAMInputFormat.java#L338 and 

https://github.com/HadoopGenomics/Hadoop-BAM/blob/master/src/main/java/org/seqdoop/hadoop_bam/BAMInputFormat.java#L407

But are not closed. Would this cause any potential issues? We are having issues loading from s3a with connections not being closed. Trying to figure out whether this would be the cause.

**Comment by akmorrow13** [comment]
@fnothaft could this be the cause of the s3a issue?

**Comment by fnothaft** [comment]
Thanks for finding those! They are definitely an issue, [but do you have `spark.hadoop.hadoopbam.bam.enable-bai-splitter` set to true](https://github.com/HadoopGenomics/Hadoop-BAM/blob/master/src/main/java/org/seqdoop/hadoop_bam/BAMInputFormat.java#L97)? If you have not set this config value, then this is not your problem.

Here is the referenced s3a issue, for anyone interested: https://github.com/bigdatagenomics/adam/issues/1906

**Comment by fnothaft** [comment]
Thanks @akmorrow13!
