### ISSUE TITLE
7.9.2 point release?

### ISSUE THREAD

**Issue by fnothaft** [HadoopGenomics/Hadoop-BAM#192]
I'd like to get a 7.9.2 point release with some of the fixes that have been made recently or that are pending:

* https://github.com/HadoopGenomics/Hadoop-BAM/pull/185
* https://github.com/HadoopGenomics/Hadoop-BAM/pull/189
* https://github.com/HadoopGenomics/Hadoop-BAM/pull/190

**Comment by fnothaft** [comment]
Ping @tomwhite.

**Comment by tomwhite** [comment]
@fnothaft, I'd be happy to make a point release with these changes. We've committed some 8.0.0 changes that shouldn't go in, and I'm not sure how to release from a branch - I'm sure it's possible, I just haven't done it before.

**Comment by fnothaft** [comment]
Hi @tomwhite! I'd be glad to put together a branch with the commits that I'd like, along with an updated release script that supports releasing off a branch. Let me know if that'd be helpful.

**Comment by tomwhite** [comment]
@fnothaft thanks for the offer - that would be great!

**Comment by tomwhite** [comment]
BTW I've merged the fixes you wanted, please let me know if there are any more.

**Comment by tomwhite** [comment]
I'd like to include #194 in the release too.

**Comment by fnothaft** [comment]
Hi @tomwhite! I'm traveling but will get a branch set up along with updated release scripts either tomorrow or Thursday. I'd prefer to exclude #194 as it changes public interfaces and should probably not go into a maintenance point release.

**Comment by tomwhite** [comment]
Thanks @fnothaft!

#194 is additive, so it won't break existing clients. We could call the release 7.10.0 if you like.

(#195 is another bugfix I'd like to release soon too.)

**Comment by fnothaft** [comment]
Hi @tomwhite! I've put together a branch with what I'd like to see at https://github.com/fnothaft/Hadoop-BAM/tree/release-7.9.2-branch. This includes scripts for releasing off of a branch, which are in commit https://github.com/fnothaft/Hadoop-BAM/commit/239eefd3bdf1af2bf8d203dbfd94b4dbc1016cb8. That last commit should logically go into trunk as well; let me know if you'd like me to open a PR against trunk with that change.

I'd be glad to include #195 in this release as it doesn't impact any functionality in ADAM. However, I am hesitant to include #194. We override the VCFOutputFormat (and possibly the VCFRecordReader) implementations in ADAM. From a bandwidth perspective, we won't be able to validate the changes in #194 before our upcoming 0.24.0 release, while we've internally validated all of the other patches in the 7.9.2 candidate branch.

**Comment by fnothaft** [comment]
Also, I will note that I haven't tested the release scripts as I don't believe that I have permissions to push Hadoop-BAM artifacts to Sonatype. That said, they're a direct port of our scripts in ADAM.

**Comment by tomwhite** [comment]
Thanks for the release script @fnothaft. I've used it to produce a 7.9.2 release. Could you try it out please and then we can close this issue?

No need to open a new PR for the script changes, as I've gone ahead and merged to master.

**Comment by fnothaft** [comment]
Thanks @tomwhite! I'm testing the release right now.

**Comment by fnothaft** [comment]
Just realized this issue was still hanging open; closing. Thanks @tomwhite!
