### ISSUE TITLE
Is gz compressed VCF file supported?

### ISSUE THREAD

**Issue by tkrishp** [HadoopGenomics/Hadoop-BAM#23]
Can someone clarify if vcf.gz is supported by VCFInputFormat?

**Comment by AndreSchumacher** [comment]
There is support for BCF which is a compressed version of VCF (similarly to BAM and SAM). See [here for a description of the format](http://www.1000genomes.org/wiki/analysis/variant-call-format/bcf-binary-vcf-version-2 ). Also most Hadoop versions should handle gzip compressed files more or less transparently but you loose the benefit of file splitting in this case.

**Comment by tkrishp** [comment]
I tried importing vcf.gz but it errors out with 'Invalid BCF format' message.
line # 56 in VCFFormat.java
       `case 0x1f: return BCF;`
This is making the framework treat gz compressed VCF file as BCF, causing the error. Let me know if I'm missing something, thanks.

**Comment by akiezun** [comment]
duplicate of #68 or vice versa - Hadoop-BAM does fail on such files. It's important to support them (VCFCodec will decode them no problem)

@AndreSchumacher can you mark one of those reports are a dup and accept a +1 vote for this feature?

**Comment by tomwhite** [comment]
Fixed in #70
