### ISSUE TITLE
Another release post Tom's CIGAR fix

### ISSUE THREAD

**Issue by davidadamsphd** [HadoopGenomics/Hadoop-BAM#30]
The CIGAR bug is blocking some validation work of GATK 4. It would be great if you could do a cut in the next few days.

**Comment by AndreSchumacher** [comment]
@davidadamsphd agreed, will do. On this topic: what do you guys think of having the latest master published automatically as SNAPSHOT to the sonatype snapshot repo? Just thinking whether this would speed up development on your side.

**Comment by davidadamsphd** [comment]
I like the idea. @akiezun, @droazen, @lbergelson, are you all OK with depending on the current snapshot of Hadoop-BAM in general (it's mostly bug fixes right now).

**Comment by akiezun** [comment]
yes for development. no for releases.

**Comment by ilveroluca** [comment]
Personally, though simple, in my opinion such a solution in the long run
tends to introduce headaches when bringing in incompatible changes. We
could also consider using the classic version branch strategy.

My 2 cents,

Luca
Il 18/nov/2015 14:51, "davidadamsphd" <notifications@github.com> ha scritto:

**Comment by davidadamsphd** [comment]
@ilveroluca, I figured it would be a mix of both: every change gets picked up in a SNAPSHOT and major backwards incompatible changes get a proper version cut.

**Comment by AndreSchumacher** [comment]
Yes, exactly, that's what I imagined. No actual changes to the way releases are done but in addition there would be snapshot artifacts published whenever they are changes to master. Other projects building on top of this should never use snapshot dependencies for their own releases, only for development. I will look into whether that could be done say on top of Travis CI which we use currently.

**Comment by AndreSchumacher** [comment]
7.3.0 is now on Sonatype.
