### ISSUE TITLE
Support reading a subset of a BAM

### ISSUE THREAD

**Issue by davidadamsphd** [HadoopGenomics/Hadoop-BAM#34]
If the Hadoop-BAM index is present, then it should be possible efficiency only load a subset of the BAM, say bases 1-2M of chromosome 5.

This will likely be picked up by the GATK team.

**Comment by fnothaft** [comment]
@davidadamsphd we've actually done this downstream in ADAM: https://github.com/bigdatagenomics/adam/blob/master/adam-core/src/main/java/org/bdgenomics/adam/io/IndexedBamInputFormat.scala. We would be glad to backport this. (cc @erictu)

**Comment by davidadamsphd** [comment]
@fnothaft, that would be awesome!

**Comment by fnothaft** [comment]
OK, great. Would folks be OK if we kept the imp'l in Scala? This might necessitate some build changes, so I can understand why a Java impl might be preferable. We would just need to revalidate, etc.

**Comment by davidadamsphd** [comment]
I'll defer to @ilveroluca and @AndreSchumacher.

**Comment by fnothaft** [comment]
Ping @ilveroluca @AndreSchumacher.

**Comment by ilveroluca** [comment]
ugh...that would also introduce significant new dependencies, to hadoop-bam
and transitively to all the projects that depend on it.  Personally I'd
prefer avoiding that.

On 20 November 2015 at 23:47, Frank Austin Nothaft <notifications@github.com

**Comment by fnothaft** [comment]
OK, we'll work on a Java port. Should be straightforward.

**Comment by AndreSchumacher** [comment]
Thanks a lot @fnothaft for offering to donate this. Happy to have it here but I agree with @ilveroluca. Let's keep things simple and stay with Java. Let me know if you don't find the time, maybe I could look into that over a weekend.

**Comment by tomwhite** [comment]
I've got a PR for this here: #59

**Comment by tomwhite** [comment]
This has now been fixed with #59.
