### ISSUE TITLE
move to Java 8

### ISSUE THREAD

**Issue by AndreSchumacher** [HadoopGenomics/Hadoop-BAM#46]
Since HTSJDK now requires Java 8 we need to ensure compatibility with 1.8 as well. I don't think we want to maintain versions to the easiest would be just to upgrade.

Based on the discussion here https://github.com/samtools/htsjdk/issues/180 it is safe to say the issue will cause controversy.

edit: We should probably start off with working on a separate branch and testing that. Also improving the test coverage would not hurt.

**Comment by droazen** [comment]
Has the proposal to move to Java 8 caused any actual controversy yet? There is at least one branch already in existence that switches the project to Java 8 and passes tests (https://github.com/HadoopGenomics/Hadoop-BAM/pull/47).

**Comment by fnothaft** [comment]
I am OK with a move to Java 8. CC @massie @heuermh @laserson @ryan-williams for further comment.

**Comment by heuermh** [comment]
We support JDK8 but do not require it, I would prefer our dependencies do the same.  If htsjdk is forcing our hand then there's not much we can do.  Nice of them to close comments on that issue and make decisions in private that affect all downstream projects.

**Comment by droazen** [comment]
@heuermh This decision was hardly made in private. There was an announcement last March on the Samtools-devel list that support for Java 6 and 7 in htsjdk would end in October 2015 (6 months after the official end of Oracle's public updates for Java 7). This announcement was followed by a one-month public comment period that took place here: https://github.com/samtools/htsjdk/issues/209. The resulting Java Minimum Version Support Policy has been posted on htsjdk's github README for almost a year now...

**Comment by ilveroluca** [comment]
In my opinion the fact that they're not supporting slightly older Java releases is still a pain, regardless of how long ago they announced it.  The time we spend chasing Java isn't spent on fixing issues or adding functionality that matters more :-(  Nevertheless, if we need it I guess we have no choice, and neither will our dependencies.

**Comment by droazen** [comment]
That's a fair complaint -- the htsjdk policy was motivated primarily by Oracle stopping support for Java 7 in April 2015, though (http://www.oracle.com/technetwork/java/eol-135779.html).

**Comment by AndreSchumacher** [comment]
Yeah I guess the only sensible thing to do is to require Java 8 as well. Let's make one more release before that and then do the move.

**Comment by fnothaft** [comment]
I think that is a reasonable approach. It sounds like the next release of Spark (2.0.0) may drop Java 7 and Scala 2.10 anyways, which would render Java 7 compatibility moot from our side.
