### ISSUE TITLE
Add code coverage reports

### ISSUE THREAD

**Issue by tomwhite** [HadoopGenomics/Hadoop-BAM#51]
It would be good to do this so we can see where test coverage needs improving. Something like https://coveralls.io would be suitable.

**Comment by tomwhite** [comment]
Here's an example report: https://coveralls.io/github/HadoopGenomics/Hadoop-BAM. Coverage is currently 26%.

**Comment by AndreSchumacher** [comment]
Wow, I expected it to be low but that's really low.
