### ISSUE TITLE
Remove support for Hadoop 1

### ISSUE THREAD

**Issue by tomwhite** [HadoopGenomics/Hadoop-BAM#54]
There hasn't been a release of Hadoop 1 since 2013, and all the distributions have been based on Hadoop 2 for a long time now.

This would involve removing references to Hadoop 1 in the documentation, as well as removing the `hadoop.org.apache.hadoop.mapreduce.lib` packages (which seem to be unused?). It would be good to mark the Hadoop dependencies as `provided`, although this could be done separately.

**Comment by ilveroluca** [comment]
We're still using Hadoop 1 on our shared cluster internally.  It's one of those "if it ain't broke, don't fix it" issues.  If it's not holding back development I'd vote to not remove the existing functionality.

**Comment by tomwhite** [comment]
Interesting to hear that. The reason I brought this up is because of I test I wrote that uses the HDFS minicluster (https://github.com/HadoopGenomics/Hadoop-BAM/pull/47/files#r5003219). Because of the differences both in APIs and Maven artifacts between Hadoop 1 and 2, it's very difficult to support both when using miniclusters.

Also, as it stands the automated tests are only run against Hadoop 2. So we don't see if any new changes break Hadoop 1 code.

**Comment by ilveroluca** [comment]
After some discussion with other Hadoop users at my organization, we've agreed to move to Hadoop 2.  I'll no longer be protesting if we decide to drop support for Hadoop 1.

**Comment by tomwhite** [comment]
Thanks @ilveroluca! That's great news.
