### ISSUE TITLE
Requests for inclusion in the next Hadoop-BAM release

### ISSUE THREAD

**Issue by cmnbroad** [HadoopGenomics/Hadoop-BAM#58]
This ticket is just to record GATK's requests for the PRs we'd like to get in to the next release of Hadoop-BAM:

https://github.com/HadoopGenomics/Hadoop-BAM/pull/47
https://github.com/HadoopGenomics/Hadoop-BAM/pull/49
https://github.com/HadoopGenomics/Hadoop-BAM/pull/50
https://github.com/HadoopGenomics/Hadoop-BAM/pull/57

The CRAM writing PR (https://github.com/HadoopGenomics/Hadoop-BAM/pull/57) has a dependency on a not-yet-released version of htsjdk (post-2.0.1) which we expect to release soon - when its ready I'll submit a PR.

**Comment by cmnbroad** [comment]
@tomwhite feel free to add/change anything I may have missed

**Comment by cmnbroad** [comment]
The new htsjdk is released. I added the version number bump to https://github.com/HadoopGenomics/Hadoop-BAM/pull/57.

**Comment by tomwhite** [comment]
I think we should include #59 in the release too.

**Comment by cmnbroad** [comment]
Would ideally like to see the fix for https://github.com/HadoopGenomics/Hadoop-BAM/issues/63 in as well.

**Comment by tomwhite** [comment]
All the issues mentioned here have been merged now, so we can close this (and do a release).

**Comment by AndreSchumacher** [comment]
Done.
