### ISSUE TITLE
Improve performance for large interval lists

### ISSUE THREAD

**Issue by tomwhite** [HadoopGenomics/Hadoop-BAM#91]
A couple of ideas from #82:
1.  Ignore the intervals for trimming/eliminating splits if there are more than a certain number (1000?), and emit a log message. (The intervals would still be used for filtering of course.)
2. For each split, discard away any interval that doesn't overlap the split. This would be done by the record reader.

**Comment by tomwhite** [comment]
I tried #2, but found that it actually makes things slower. Presumably because checking if each interval overlaps the split is slow, compared to the optimized checking that OverlapDetector performs.

**Comment by tomwhite** [comment]
Fixed in #121.

**Comment by lbergelson** [comment]
Is the performance with intervals still worse than the performance without interval lists?

**Comment by droazen** [comment]
If yes, I think we might want to keep this issue open

**Comment by tomwhite** [comment]
@lbergelson, yes it is.

As it currently stands running CountReadsSpark (from GATK) on a 133 GB BAM takes 2.17 minutes when no intervals are specified, and 7.26 minutes when a human exome interval list (180K intervals) is used. This is over 3 times slower. It's a lot faster than it was (due to the fix in #121), but we can do better.

The reason that it is slower when using a long intervals list is because the filtering happens after each read has been read from the BAM. If we could do the filtering by skipping portions of the BAM file that don't overlap (like HTSJDK does) then we can do a lot better.

I mocked up some code to do this, and the time was 1.73 minutes - 20% faster than the no intervals case.

See https://github.com/HadoopGenomics/Hadoop-BAM/compare/master...tomwhite:intervals-optimization-experiment

* The main idea is to add the chunk intervals for each split into the FileVirtualSplit class, so that each record reader can use that information to only read the chunks in the BAM file that it needs to, rather than read everything and apply filtering afterwards.
* This change means that an index is always needed when using intervals. I think that's probably reasonable.
* BAMRecordReader changes to use an iterator from SamReader, rather than manage its own iteration (via BAMRecordCodec).
* There is no provision in htsjdk to access the underlying reader, in this case BAMFileReader, and in particular seek to a known point in the block compressed stream (BGZF stream). This is needed by Hadoop-BAM to process splits in parallel. I had to expose some parts of BAMFileReader to get this to work. See https://github.com/samtools/htsjdk/compare/master...tomwhite:tw_expose_underlying_sam_reader
* BAMFileReader also does intervals processing before iterating, which is not what we want when reading in parallel: we need to process the intervals once, to minimize per task initialization. (With the exome list, pre-processing takes ~10s.)
* There's some code to convert intervals to QueryInterval, which I took from SamReaderQueryingIterator. It might be useful to move that class to htsjdk.
* Some tests fail due to off-by-one errors. In particular there's some interaction with the code to keep paired reads together. This will probably take a little while to get working.

If this looks like an improvement, can you help get the changes into htsjdk to expose the parts we need? (The way I've done it for the mock up could be improved.) In general I'd like to delegate as much as possible to htsjdk.

**Comment by droazen** [comment]
Sounds like a (big) improvement to me! If you open a PR for the htsjdk piece I can review and make suggestions on the approach taken.

**Comment by tomwhite** [comment]
Thanks @droazen. I have now written a proper implementation of this split across htsjdk, Hadoop-BAM, and GATK. Please take a look!
* https://github.com/samtools/htsjdk/pull/786/files
* https://github.com/HadoopGenomics/Hadoop-BAM/pull/122
* https://github.com/broadinstitute/gatk/pull/2350
