### ISSUE TITLE
Can I output normal text files using HadoopBAM

### ISSUE THREAD

**Issue by aschle** [HadoopGenomics/Hadoop-BAM#95]
Is it possible to use HadoopBAM to analyse reads? I would like to count the mapped/unmapped reads at each position? I just read it can manipulating BAM/SAM files. I am new to this area and could't find any other help, sorry.

I would like to change the `OutputFormat` to normal text instead of a new BAM file. So my `InputFormat` would still be `BAMInputFormat`, but the `OutputFormat` should be instead of `KeyIgnoringBAMOutputFormat` a `TextOutputFormat` (`org.apache.hadoop.mapred.TextOutputFormat`).

How would I do that?

**Comment by ilveroluca** [comment]
I take it you're writing your own Hadoop application to perform this analysis?  The default output format is already the TextOutputFormat class.  You simply need to `write` out your output as `Text` into the context.  On the other hand, to read BAM or SAM you'll need to `setInputFormat` to the appropriate Hadoop-BAM class (say `BAMInputFormat` or `SAMInputFormat`).

**Comment by aschle** [comment]
Yes! I see. Sorry for bothering you. Everything is working as expected now!
